Repository GSG-G10/NAR-Restaurant, pull requests merged in 2021-07, with the labels that each got.

#6 create file structure
  .gitignore
  images/logo.png
  index.html
  package-lock.json
  package.json
  script/dom.js
  script/index.js
  style/index.css
  test/index.test.js
Labels: Awaiting Review

#8 create html file
  index.html
Labels: Awaiting Review

#10 style for index page
  index.html
  style/index.css
Labels: Awaiting Review

#11 create functions to create cards
  index.html
  script/index.js
Labels: in-progress

#14 create display
  script/index.js
Labels: Awaiting Review

#18 final result in js
  index.html
  script/dom.js
  script/index.js
  style/index.css
Labels: Awaiting Review

#20 update display data
  script/dom.js
  script/index.js
Labels: Awaiting Review

#21 modify cards style and some others
  images/logo.png
  images/logo2.png
  index.html
  style/index.css
Labels: Awaiting Review

#22 create readme about project
  README.md
  index.html
Labels: Awaiting Review

#25 Create hero section
  images/hero.png
  images/pattern1.png
  index.html
  style/index.css
Labels: Awaiting Review

#27 #23 refactor html
  index.html
  script/dom.js
  script/index.js
  script/xhr.js
  style/index.css
Labels: Awaiting Review

#28 modify navlinks and hero section
  index.html
  script/dom.js
  style/index.css
Labels: Awaiting Review

#30 handle the respond status
  script/dom.js
  script/xhr.js
Labels: Awaiting Review

#37 remove empty files
  .gitignore
  package-lock.json
  package.json
  test/index.test.js
Labels: Awaiting Review

#38 edit the number of show data
  script/dom.js
Labels: Awaiting Review

#39 add isVideo parameter
  script/dom.js
Labels: Awaiting Review

#40 add trim function to input value
  script/dom.js
Labels: Done

#41 xhr else block
  script/xhr.js
Labels: Done

#42 split event listener
  script/dom.js
Labels: Done
